### ISSUE TITLE
请问安装组件模板后build报错

### ISSUE THREAD

**Issue by RedmondLee** [vv13/vue-cli-multipage#3]
git clone以后能正常编译。
但将其他单页面SPA页面整合进来时发现npm run build报错。
经测试安装了[Buefy](https://github.com/buefy/buefy)这个模板后运行会提示以下报错信息

```
PS C:\vues\news> npm run build

> vue-cli-multipage@0.1.0 build C:\vues\news
> vue-cli-service build

 ERROR  TypeError: Cannot read property 'version' of undefined
TypeError: Cannot read property 'version' of undefined
    at module.exports (C:\vues\news\node_modules\@vue\cli-plugin-eslint\index.js:20:27)
    at C:\vues\news\node_modules\@vue\cli-service\lib\Service.js:78:7
    at Array.forEach (<anonymous>)
    at Service.init (C:\vues\news\node_modules\@vue\cli-service\lib\Service.js:76:18)
    at Service.run (C:\vues\news\node_modules\@vue\cli-service\lib\Service.js:215:10)
    at Object.<anonymous> (C:\vues\news\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-cli-multipage@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-cli-multipage@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-03-18T04_52_00_285Z-debug.log
```

搜索源码未找到version相关的代码段（很菜），请问有办法修复吗？
谢谢

**Comment by vv13** [comment]
你好，我刚测试了下，安装Buefy并全局引入后，是可以正常build的，您是否可以folk一下，并提供一个重现问题的最简化工程代码呢？

**Comment by RedmondLee** [comment]
您好，感谢回复。fork地址https://github.com/RedmondLee/vue-cli-multipage
具体操作步骤：

```
git clone https://github.com/RedmondLee/vue-cli-multipage.git
cd ..... #省略切换目录
vpm insatll buefy
rm -rf .../src/pages  &&  mkdir pages 
# 覆盖github下载源码，实际更改了pages/index/main.js 和 App.vue两个文件
```

**Comment by vv13** [comment]
> 您好，感谢回复。fork地址https://github.com/RedmondLee/vue-cli-multipage
> 具体操作步骤：
> 
> ```
> git clone https://github.com/RedmondLee/vue-cli-multipage.git
> cd ..... #省略切换目录
> vpm insatll buefy
> rm -rf .../src/pages  &&  mkdir pages 
> # 覆盖github下载源码，实际更改了pages/index/main.js 和 App.vue两个文件
> ```

clone了你的repo，发现package.json中没包含buefy，然后我执行`npm i buefy`后能成功编译：
```
➜   npm run build

> vue-cli-multipage@0.1.0 build /Users/xxx/vue-cli-multipage
> vue-cli-service build


⠋  Building for production...

  File                                      Size             Gzipped

  dist/chunk-vendors/js/chunk-vendors.b3    307.26 KiB       80.78 KiB
  9ffc0a.js
  dist/index/js/index.3d740bad.js           2.15 KiB         1.05 KiB
  dist/chunk-vendors/css/chunk-vendors.c    328.77 KiB       40.17 KiB
  21c8416.css

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
```

建议检查版本 npm>6，node>10
